### ISSUE TITLE
problem with crop

### ISSUE THREAD

**Issue by darlanmendonca** [nisaacson/pdf-text-extract#23] opened 2016-11-23 13:34 UTC
hey guys, I'm trying your module, I need crop just part of a page

I used

```js
const options = {
  crop: {
    x: 0,
    y: 100,
    w: 335,
    h: 465,
  },
}

extract(filePath, options, function (err, pages) {
  if (err) {
    console.dir(err)
    return
  }
  console.dir(pages)
})
```

but the crop dont works, I receive the text of entire page

I'm using the crop wrong? Please, guide me about it

**Comment by nisaacson** [comment] 2017-02-15 16:04
@darlanmendonca the 1.4.1 missing from master is now fixed. See issue #19. If you are still looking at this a PR should work as intended

**Comment by gfmoore** [comment] 2018-11-22 14:14
Hi, I too am trying this crop function which would be very useful.

I cannot get darlanmendonca's solution to work.

The last post by TechplexEngineer seems to indicate that the fix is now in the code?

What units are being used for the co-ordinates - pixels?

If I try the commenting out idea for line 19 I often get an error from the basic code at console.write(err)

var path = require('path')
var filePath = path.join(__dirname, './Eng_Report.pdf')

var extract = require('pdf-text-extract')

const options = {
  crop: {x: 1, y: 1, w: 200, h: 200}  //not working
};

extract(filePath, options, function (err, pages) {  
  if (err) {
    console.dir(err)
    return
  }
  console.log(pages[0])
})

What is supposed to happen if no text is found within the crop area?

Thanks

**Closed** 2019-01-01 13:30 UTC
